// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5LCZ8xALRyn5m-uhtUhhhUMDBHiRj8Ko',
    appId: '1:921607986753:web:5f449e7c0d7118642230c0',
    messagingSenderId: '921607986753',
    projectId: 'inventorymanagement-5bd13',
    authDomain: 'inventorymanagement-5bd13.firebaseapp.com',
    storageBucket: 'inventorymanagement-5bd13.firebasestorage.app',
    measurementId: 'G-9X42YZ69P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRc-dUBc7KgXm3FWojmyyA8Jb7ZK237Q',
    appId: '1:921607986753:android:50ef5d338ab340a02230c0',
    messagingSenderId: '921607986753',
    projectId: 'inventorymanagement-5bd13',
    storageBucket: 'inventorymanagement-5bd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfiCRo0_7tKZHQwwqZCa1Zdjtqg3dEIs',
    appId: '1:921607986753:ios:c0bfc58ff26c525f2230c0',
    messagingSenderId: '921607986753',
    projectId: 'inventorymanagement-5bd13',
    storageBucket: 'inventorymanagement-5bd13.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfiCRo0_7tKZHQwwqZCa1Zdjtqg3dEIs',
    appId: '1:921607986753:ios:c0bfc58ff26c525f2230c0',
    messagingSenderId: '921607986753',
    projectId: 'inventorymanagement-5bd13',
    storageBucket: 'inventorymanagement-5bd13.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5LCZ8xALRyn5m-uhtUhhhUMDBHiRj8Ko',
    appId: '1:921607986753:web:45310c922db8f80d2230c0',
    messagingSenderId: '921607986753',
    projectId: 'inventorymanagement-5bd13',
    authDomain: 'inventorymanagement-5bd13.firebaseapp.com',
    storageBucket: 'inventorymanagement-5bd13.firebasestorage.app',
    measurementId: 'G-BBL8WBT6Y7',
  );
}